# Generated by Django 4.1.5 on 2023-01-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveIntegerField(default=0, verbose_name='Kilometraje')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('costo', models.PositiveSmallIntegerField(default=0, verbose_name='Costo')),
                ('fecha', models.DateField(verbose_name='Fecha de inicio')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.auto', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
